spring:
  application:
    name: WorkflowDemo
  datasource:
    url: jdbc:mysql://localhost:3306/workflowdemo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 1000
  jpa:
    hibernate:
      ddl-auto: update
  threads:
    virtual:
      enabled: true
workflow:
  # Redis状态超时时间，默认为24 * 60 * 60 = 86400秒
  expire-time: 86400
  # 结果处理线程超时时间，默认为 30 * 1000 = 30000毫秒
  result-time-out: 600000